# Generated by Django 5.1.1 on 2024-09-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_minor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='user',
        ),
    ]
